name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup libharu
        uses: ./

  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup libharu
        uses: ./
        with:
          libharu-version: 2.4.3